### ISSUE TITLE
Include Chosen Hero to Table

### ISSUE THREAD

**Issue by benjamin-small** [poma/HotsStats#16]
After the match has started, I'm not thinking "oh it's xXLovesToSpoonXx". I'm thinking "That mf'n graymane, what's his deal?". Having to do the associative mapping is a distraction and makes the app less useful.

**Comment by poma** [comment]
That's what I do in full table after first minute. Before that I have no idea which heroes are selected.

**Comment by benjamin-small** [comment]
So it's not flushing the selected heroes to the log file before it's loading the map? Bummer.
