### ISSUE TITLE
0.4.2  Doesn't show only my stats , no mute on hots logs , any suggestions ?

### ISSUE THREAD

**Issue by Tomazzz007** [poma/HotsStats#19]
It just doesn't show only my stats , everybody's else are ok .
Just double check that i dont have mute , so i dont know what the problem is , please help .
Thanks.
![1](https://cloud.githubusercontent.com/assets/17932567/13886561/7fd5c356-ed48-11e5-8802-121d92709725.jpg)

**Comment by poma** [comment]
Looks like hotslogs correctly return all data for your battletag. Can you please post `C:\Users\<user>\AppData\Local\Temp\Heroes of the Storm\TempWriteReplayP1\replay.server.battlelobby` file? It exists only during match and loading screen.

**Comment by Tomazzz007** [comment]
Looks like it started to work , idk what was the problem ...
Thanks for looking anyway !
![1](https://cloud.githubusercontent.com/assets/17932567/13895734/7d402dbc-ed88-11e5-891c-89596d1c7439.jpg)
