### ISSUE TITLE
[Req] Show QM and HL MMR on stats screen

### ISSUE THREAD

**Issue by wolfposd** [poma/HotsStats#27]
Would be nice if the stats-screen either:
- had a button to toggle between QM and HL
- showed both QM and HL MMR

**Comment by AndrewPalozzo** [comment]
Agree. So often I forget to change this, based on the game type I'm playing.

**Comment by poma** [comment]
We can update table dynamically when you change game type in settings. Will
that be ok?

**Comment by AndrewPalozzo** [comment]
Yeah, I think having it change when you modify the setting would be better... But maybe showing both could be useful too.

**Comment by poma** [comment]
done. will be in v5.1
