### ISSUE TITLE
Broken for new patch

### ISSUE THREAD

**Issue by willbonney** [poma/HotsStats#29]
Will it be fixable?
![image](https://cloud.githubusercontent.com/assets/1846500/14139983/132e5848-f6a9-11e5-99fa-8d5cbb0463ac.png)

**Comment by isbecker** [comment]
Also having this issue.

**Comment by isbecker** [comment]
Fixed in v0.4.4

**Comment by poma** [comment]
Please before creating an issue check for updates. It was fixed before this issue was created.
