### ISSUE TITLE
Bug in latest version

### ISSUE THREAD

**Issue by Inrego** [poma/HotsStats#32]
In the latest version, I ran into this: http://i.imgur.com/68XwRVt.png
It's not the first time I see someone with a single letter on your window, when there are in fact no one with just a single letter. This is the first time it caused to much trouble, though.

**Comment by Inrego** [comment]
It seems to happen when there's a russian on one of the teams.

EDIT: nvm, happens every time.

**Comment by Stanzilla** [comment]
Yup, seems to be a cyrillic problem :)

![hotsstats_2016-04-02_22-12-28](https://cloud.githubusercontent.com/assets/75278/14228788/4d2373d4-f920-11e5-9040-fa8725baf649.png)

**Comment by poma** [comment]
Yes this is a bug with battle tag extraction. See notes for [release 0.4.4](https://github.com/poma/HotsStats/releases/tag/v0.4.4) for details.

**Comment by Inrego** [comment]
For me it happens consistently in every single game.

**Comment by poma** [comment]
it happens when nicknames contain non-latin letters (2+ byte unicode symbols). I'm not sure how to fix it for new file format.

**Comment by poma** [comment]
Improved battle tag extraction. Will be released in v5.1. Closing this issue until we find any problems in 5.1
