### ISSUE TITLE
Time CCd enemy heroes is wrong

### ISSUE THREAD

**Issue by ghost** [poma/HotsStats#34]
I played a 17 min 46 sec round on Tomb of the Spider Queen as Anub'arak. In the post-game summary screen, it shows that my "Time CCd enemy heroes" was 37 min 22 sec. Screenshot and replay attached.

My build was:

1 - Regen Master
4 - Underking
7 - Leeching Scarabs
10 - Cocoon
13 - Chitinous Plating
16 - Epicenter
20 - Rewind

![2016-04-04 16_36_14-heroes of the storm](https://cloud.githubusercontent.com/assets/8107645/14262537/1161f0c2-fa84-11e5-9f43-c98db1e5fcc6.png)

[Tomb of the Spider Queen (31) 37min CC.zip](https://github.com/poma/HotsStats/files/203301/Tomb.of.the.Spider.Queen.31.37min.CC.zip)

**Comment by poma** [comment]
Currently all stats are calculated by HotS and stored in replay file. I just show them and can't really do anything to calculations.

Also keep in mind that CC time counts any CC including slows so heroes like Murky and Stitch will always have insane amounts. Not sure how you got such number with Anub though.
