### ISSUE TITLE
Program crashes when file already in use

### ISSUE THREAD

**Issue by Kline-** [poma/HotsStats#38]
I leave Hotslogs replay uploader running, so maybe that is the conflict, but this app crashes if it tries to open the replay for the end-of-game stats screen and it's already in use. Two screenshots attached of the errors generated.
![capture](https://cloud.githubusercontent.com/assets/1126350/14510826/13aa7342-0199-11e6-853f-cabf311c4788.PNG)
![capture1](https://cloud.githubusercontent.com/assets/1126350/14510825/13a7f586-0199-11e6-90c2-a8cedcf632f4.PNG)

**Comment by Stanzilla** [comment]
Dupe of https://github.com/poma/HotsStats/issues/36

**Comment by Kline-** [comment]
Didn't realize the commit to close #36 was after the latest release, sorry!
