### ISSUE TITLE
App Crash when using Hotkey / not showing automatically

### ISSUE THREAD

**Issue by Flom1982** [poma/HotsStats#44]
It worked fine for me until some weeks ago, but I didn't do any system changes or sth.

This is what the log.txt says:

[2016-05-16 12:43:27.9301] FATAL: Domain unhandled exception System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei StatsDisplay.App.<SetupHotkeys>b__14_0(Object o, EventArgs e) in C:\Dev\HotsStats\StatsDisplay\App.xaml.cs:Zeile 72.
   bei StatsDisplay.Helpers.HotKey.ComponentDispatcherThreadFilterMessage(MSG& msg, Boolean& handled) in C:\Dev\HotsStats\StatsDisplay\Helpers\HotKey.cs:Zeile 71.
   bei System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSG& msg)
   bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   bei System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   bei System.Windows.Application.RunDispatcher(Object ignore)
   bei System.Windows.Application.RunInternal(Window window)
   bei System.Windows.Application.Run(Window window)
   bei StatsDisplay.App.Main() in C:\Dev\HotsStats\StatsDisplay\obj\Release\App.g.cs:Zeile 0.

**Comment by poma** [comment]
I'm not sure how this is possible. Maybe someone can help? 

I have a null reference check before invoking Show method. Here is the relevant piece of code:

            _hotKey.Pressed += (o, e) => {
                if (_currentWindow?.IsVisible ?? false) {
                    _currentWindow.Hide();
                } else {
                    _currentWindow.Show();
                }
            };

NullReferenceException is thrown on line where ` _currentWindow.Show()` is called in App.xaml.cs line 72.
