### ISSUE TITLE
HotsStats errors and Shift+Tab stops working.

### ISSUE THREAD

**Issue by Hasbro35** [poma/HotsStats#49]
Hi Guys...wish i could give a better description but i have been consistently getting errors in HotStats 0.54 on Windows 10.  Can't quite lock down the cause.  A restart of HotsStats fixes the issue till the next error.  I am usually restarting hotstats before every game I play in HotS.

Scenarios:
1. Most common issue is that HotsStats will display its screen but will Shift+Tab will not work after using it the first time to see HotsStats.  Most commonly on the final screen in phase 3 the screen will only partially paint and then Shift+Tab'ing won't work.  If i close the phase 3 window and start a new game the phase 1 window will display, but then locks up and won't allow a Shift+Tab out of it.  So a restart is required.
2. Another scenario is that HotsStats will run and i can see the first phase screen, but then at the end of the game i realize the app has crashed with an error. 

In all cases the same errors seem to be logged, so probably the same issue.
I am using an Acer Aspire V Nitro Laptop on Windows 10 64bit with the latest Geforce drivers
HotsStats is 0.54 and I installed it with the setup.exe

I have attached my most recent log file and am happy to test any builds you want me to look at.
[log.txt](https://github.com/poma/HotsStats/files/480695/log.txt)

**Comment by poma** [comment]
Probably because of new HotS version. I've updated replay parser but can't check it myself. Try this one 
[Setup.zip](https://github.com/poma/HotsStats/files/481368/Setup.zip)

**Comment by Hasbro35** [comment]
Hi Roman,

Thanks...I will try it tonight and let you know.

Best,

Chris Hasbrouck
626-354-0032

**Comment by Hasbro35** [comment]
Getting a similar error and same issue.  
[log.txt](https://github.com/poma/HotsStats/files/481770/log.txt)

**Comment by poma** [comment]
I currently don't have HotS installed. Can you upload one of your replays?

**Comment by Hasbro35** [comment]
Here is a replay from a game I played last night
[Replay.zip](https://github.com/poma/HotsStats/files/483280/Replay.zip)

**Comment by Hasbro35** [comment]
I think you can close this one.  0.6.1 seemed to fix it for the most part.
