### ISSUE TITLE
Missing comma

### ISSUE THREAD

**Issue by Stanzilla** [poma/HotsStats#9]
Looks like the % values are missing a comma ![heroesofthestorm_x64_2016-03-16_03-13-10](https://cloud.githubusercontent.com/assets/75278/13800031/2161ab0c-eb25-11e5-8887-00e24fc09e4f.png)

**Comment by Stanzilla** [comment]
@poma this seems to be back in 4000f588d22e3b2490a215ceafc68ddc47c35ba9

**Comment by poma** [comment]
weird. I double checked and current code seems to be correct.

**Comment by Stanzilla** [comment]
Yeah it's weird, I compiled it myself and it shows like this 

![image](https://cloud.githubusercontent.com/assets/75278/13902628/e820d5ce-ee4f-11e5-915a-ccfd1fba05ed.png)

**Comment by poma** [comment]
If you have Visual Studio installed you can find this bug yourself. Win rate parsing is done in FileProcessor.cs line 117

**Comment by Stanzilla** [comment]
Recompile dll, works again, sorry
